### ISSUE TITLE
第9届社区分享会

### ISSUE THREAD

**Issue by BLumia** [deepin-community/.meeting#10]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

待定

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2023年6月12日（周一）北京时间15:00
会议号：115-403-842
也可使用入会链接：https://work.weixin.qq.com/webapp/tm/lexv0LJEDTb

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

### 第一部分：obs集成玲珑构建进展

https://github.com/deepin-community/.meeting/assets/10095765/05a7b903-1188-4c4b-96b8-bf22fc76f97f

### 第二部分：xdg-desktop-portal-dde 到 DTK统一版本管理进度报告

https://github.com/deepin-community/.meeting/assets/10095765/ba8a7547-0be8-4434-b6e9-1ef0978b784f

## 会议纪要

本次分享会共四位人员分享了五个方面的主题，分别是：

1. myml 分享了关于 obs 集成玲珑构建的相关进展，以及对向玲珑仓库中递交软件包的方式、包维护过程中所涉及到的文件等进行了详细的介绍。
2. Decodetalkers 介绍了 xdg-desktop-portal-dde 项目的现状，以及后续要做的方向。
3. Decodetalkers 也对第三方的 greetd 项目进行了概要介绍
4. BLumia 介绍了 distrobox 的简要应用方式
5. asterwyx 介绍了当前对 DTK 统一版本管理的相关自动化流程的编写进展，并进行了相关的简要用法演示。

## 参与人员

![image](https://github.com/deepin-community/.meeting/assets/10095765/289c8f18-e569-4664-bc52-0b9fcbccfb2a)

**Comment by myml** [comment]
分享话题：obs集成玲珑构建进展
相关链接：https://github.com/linglongdev/repo

内容概要：分享obs构建玲珑的流程

**Comment by Decodetalkers** [comment]
分享话题:  xdg-desktop-portal-dde
相关链接: https://flatpak.github.io/xdg-desktop-portal/index.html

内容分享: 后端的功能，上游将要有的改动，和未完成的地方

相关话题: greetd,一个新的desktop manager
相关链接:https://github.com/kennylevinsen/greetd

内容分享：它大概做的，简单的实现等

**Comment by BLumia** [comment]
分享话题：distrobox 简介
相关链接：https://bbs.deepin.org/post/257787
内容概要：介绍 distrobox 的基本用法，以及与 deepin 的关系，旨在建议更多社区用户了解这种用法，并尽可能避免进行不同发行版混源的操作。

**Comment by asterwyx** [comment]
分享话题：DTK统一版本管理进度报告
相关链接：https://github.com/asterwyx/dtk-update-bot https://github.com/peeweep-test/dtk
内容概要：介绍统一版本管理方案的进度
