### ISSUE TITLE
第17届社区分享会

### ISSUE THREAD

**Issue by dengbo11** [deepin-community/.meeting#18]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

@dengbo11

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2023年10月16日（周一）北京时间15:00
会议号：550-996-584

也可使用入会链接：https://meeting.tencent.com/dm/MuKZWZl9Hmea

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

## 录屏/录音

[vedio](https://github.com/deepin-community/.meeting/assets/23466548/6fa7b2a0-d68b-45e8-bfdd-3075d6ceb72c)

### dde-launchpad 进度演示
@BLumia 介绍了dde-launchpad的最新进展，并演示最新启动器的功能

### dbuspy
@black-desk 介绍了dbuspy的设计框架，并进行功能展示

### Layer Shell 实现
@wineee 介绍了窗管中设置层级，锚点布局的协议，并进行功能演示

### 输入法进度展示
@dengbo11 介绍了输入法的最新进展，以及后期开发计划

### treeland greeter 集成DA认证
@justforlxz 介绍了treeland greeter的最新进展及后期开发计划

**Comment by BLumia** [comment]
分享话题：dde-launchpad 进度演示
相关链接：https://github.com/linuxdeepin/dde-launchpad
概述：近期 dde-launchpad 的完成进度演示，包括焦点切换、消除隐藏窗口延迟、输入即搜索、简拼支持。

**Comment by black-desk** [comment]
分享话题: dbuspy
相关链接: https://textual.textualize.io 
概述:
	最近业余用一个python的TUI应用程序框架  写了一个类似d-feet的小工具 尚未完工.

**Comment by wineee** [comment]
分享话题：Layer Shell 实现
相关链接：https://github.com/vioken/waylib/pull/187
概述：实现 wayland 窗管中设置层级，锚点布局的协议（尚未完工）

**Comment by dengbo11** [comment]
分享话题：输入法进度展示
相关链接：https://github.com/linuxdeepin/deepin-im
概述：输入法跨框架（fcitx和ibus)无缝切换及后期工作计划。

**Comment by justforlxz** [comment]
分享话题：treeland greeter 集成DA认证
相关链接：N/A
概述：将 DA 认证集成到 greeter 模块中（测试中）

**Comment by kegechen** [comment]
[video](https://github.com/deepin-community/.meeting/assets/23466548/6fa7b2a0-d68b-45e8-bfdd-3075d6ceb72c)

@dengbo11
