### ISSUE TITLE
第19届社区分享会

### ISSUE THREAD

**Issue by hudeng-go** [deepin-community/.meeting#20]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

@hudeng-go 

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2023年11月13日（周一）北京时间16:00
会议号：749-968-118
也可使用入会链接：https://meeting.tencent.com/dm/CrdsiDaNISqs

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

## 录屏/录音

https://github.com/deepin-community/.meeting/assets/69233028/acc47fbf-198c-42c1-9fd3-d360b7dd6a45

### dde-launchpad 相关进度演示

@BLumia 介绍了[launchpad](https://github.com/linuxdeepin/dde-launchpad)的界面调整以及新功能，界面调整这块把搜索框和展开按钮从底部移到了底部；同时添加了按字母应用的分类、并支持分类的点击和搜索，同时支持搜索键盘焦点切换等，本周计划修复并提测几个已知bug。

### treeland 相关进度演示

@justforlxz 介绍目前[treeland pr20](https://github.com/vioken/treeland/pull/20)添加了[ext_foreign_toplevel_list_v1](https://wayland.app/protocols/ext-foreign-toplevel-list-v1)协议获取并向[dde-dock](https://github.com/linuxdeepin/dde-dock)提供窗口列表的支持（丐版协议，完全版协议是草案状态），同时提供查询窗口管理的pid的支持。

### waylib输入法支持

@asterwyx 介绍了[waylib](https://github.com/vioken/waylib)输入法支持的相关背景和进展：为[treeland](https://github.com/vioken)窗管的输入法支持做准备，目前在waylib中添加了[input-method-unstable-v2](https://doc.qt.io/qt-6/qtwaylandcompositor-attribution-wayland-text-input-unstable-v2.html)和[text-input-unstable-v3](https://wayland.app/protocols/text-input-unstable-v3)协议转fcitx5的支持，这周继续支持更老版本的v1，提供更好的应用兼容性。

### layershell封装及其xorg模拟，及其dock进度

@tsic404 介绍目前已经完成[dde-shell](https://github.com/linuxdeepin/dde-shell)的layershell封装，用于提供dde-dock使用的窗口布局管理，并在支持wayland的现状下扩展了xorg的支持；同时完成[dde-dock](https://github.com/linuxdeepin/dde-dock)的panel开发以及部分任务管理功能，该功能同样以dde-shell插件形式对接[am](https://github.com/linuxdeepin/dde-application-manager)实现。

### 多项目关联topic进行开发和提测
@hudeng-go 介绍使用[topic](https://github.com/deepin-community/.test-infra/tree/dev/prow/plugins/topic)插件实现关联的多项目开发和提测：
- `/topic testTopicName` 该评论的github pr关联到topic
- `/remove-topic testTopicName` 该评论的github pr取消关联到topic
- `/integr-topic testTopicName` 任意topic关联的github pr输入该评论进入提测流程
- 提pr的head分支包含`topic-testTopic`前缀的自动关联到`testTopic`中

ps： 功能实现上使用github project,上述功能目前不支持跨组织。

**Comment by BLumia** [comment]
分享话题：dde-launchpad 相关进度演示
相关链接：https://github.com/linuxdeepin/dde-launchpad
概述：近期 dde-launchpad 的完成进度介绍，包括新的字母表排序索引界面，0.2.0 tag 以及后续计划

**Comment by justforlxz** [comment]
分享话题：treeland 相关进度演示
相关链接：https://github.com/vioken/treeland/pull/20
概述：支持了 ext_foreign_toplevel_list_v1 协议和为 dock 提供的 ztreeland_foreign_toplevel_manager_v1 扩充协议。

**Comment by hudeng-go** [comment]
分享话题： 多项目关联topic进行开发和提测
相关链接：https://github.com/deepin-community/.test-infra/tree/dev/prow/plugins/topic
概述： 使用github project方式关联管理topic,topic支持自动关联，也可手动在pr中评论`/topic topicname`，在集成阶段在任意关联topic关联pr中命令`/integr-topic topicname`可以一次性集成topic内所有项目。

**Comment by asterwyx** [comment]
分享话题：waylib输入法支持
相关链接：https://github.com/vioken/waylib
概述：现在waylib中已支持input-method-unstable-v2和text-input-unstable-v3协议，支持这两种协议的输入法和客户端现已可以输入中文。

**Comment by tsic404** [comment]
分享话题：layershell封装及其xorg模拟，及其dock进度。
相关链接：https://github.com/linuxdeepin/dde-shell
概述：dde-shell 完成了layershell的封装和xorg上行为的模拟，可以使用其相关接口完成窗口的锚定，分层，独占区域等操作。dde-shell中使用layershell及其模拟开发的新dock已经完成了最基本的panel。
