### ISSUE TITLE
第20届社区分享会

### ISSUE THREAD

**Issue by Zeno-sole** [deepin-community/.meeting#21]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

@Zeno-sole 

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2023年11月27日（周一）北京时间15:00
会议号：375357359
也可使用入会链接：https://meeting.tencent.com/dm/V9YaUh7ocF8u

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

## 录屏/录音

[录屏](https://github.com/deepin-community/.meeting/releases/download/untagged-40982a62a32b74db70b9/2023-11-27.15-03-03.mp4)

## 会议纪要
1.  介绍了deepinv23对 arm fvp支持，  proot-distro介绍
2.  dde-launchpad 进度演示，介绍了对Qt6适配进度以及近期完成的拖拽小功能
3.  关于cmake各种使用方法，[black-desk](https://github.com/black-desk) 分享了一本关于cmake的书，还分享了一个自己写的生成各种cmake的脚本
4. treeland 进度演示，介绍了treeland客户端/服务端装饰器相关功能

**Comment by chenchongbiao** [comment]
分享话题：arm fvp 和 proot-distro
相关链接：
arm fvp
https://github.com/chenchongbiao/deepin-img 
https://github.com/chenchongbiao/arm-reference-solutions-build-scripts
https://github.com/chenchongbiao/arm-reference-solutions-run-scripts

proot-distro
https://github.com/termux/proot-distro/pull/376
概述：arm fvp 对 deepin v23 系统支持，proot-distro 对 deepin v23 支持

**Comment by BLumia** [comment]
分享话题：dde-launchpad 相关进度演示
相关链接：https://github.com/linuxdeepin/dde-launchpad
概述：近期 dde-launchpad 的完成进度介绍，包括0.2.1 tag，全屏启动器界面的拖拽功能（未涵盖在 0.2.1 tag），以及后续计划

**Comment by black-desk** [comment]
分享话题: 稍微有一点点摩登的 cmake
相关链接:
- https://crascit.com/professional-cmake/
- https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs
- https://github.com/black-desk/PFL.cmake
- https://github.com/cpm-cmake/CPM.cmake
- https://github.com/black-desk/GitSemver.cmake

**Comment by justforlxz** [comment]
分享话题：treeland 相关进度演示
相关链接：https://github.com/linuxdeepin/treeland
概述：treeland 移动到 linuxdeepin下；treeland支持客户端/服务端装饰器。

**Comment by Zeno-sole** [comment]
会议纪要：&nbsp;
记录人： Zeno
1.&nbsp; 介绍了deepinv23对 arm fvp支持，&nbsp; proot-distro介绍
2.&nbsp; dde-launchpad 进度演示，介绍了对Qt6适配进度以及近期完成的拖拽小功能
3.&nbsp; 关于cmake各种使用方法，[black-desk](https://github.com/black-desk) 分享了一本关于cmake的书，还分享了一个自己写的生成各种cmake的脚本
4. treeland 进度演示，介绍了treeland客户端/服务端装饰器相关功能





&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;;
发送时间:&nbsp;2023年11月27日(星期一) 凌晨4:43
收件人:&nbsp;"deepin-community/.meeting"<&gt;; 
***@***.***&gt;; "Your ***@***.***&gt;; 
主题:&nbsp;Re: [deepin-community/.meeting] 第20届社区分享会 (Issue #21)

&nbsp;



 
Reopened #21.
