### ISSUE TITLE
第22届社区分享会

### ISSUE THREAD

**Issue by l631197874** [deepin-community/.meeting#23]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

@l631197874 

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2023年12月25日（周一）北京时间15:00
会议号：#腾讯会议：833-401-746
也可使用入会链接：https://meeting.tencent.com/dm/mOrISgo9N90E

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

## 录屏/录音

https://github.com/deepin-community/.meeting/assets/58616982/05a53155-1cfd-4d33-88fa-10ef1f37189f

## 会议纪要
justforlxz:
Treeland 大写锁定提示，密码输入默认不显示功能，用户列表切换等功能完成
添加新协议协议，由向合成器申请贴图，让合成器为桌面背景贴图，不由程序自己去贴图来完成桌面背景切换，可以减少内存消耗

Blumia: 
讲解direnv 的作用，在shell 的情况下，切换到某个目录时，帮助自动配置环境变量。以及如何配置direnv环境

Tisic:
dock 分进程插件介绍，解决dock经常卡住的问题，将dock 中的插件分解成独立子进程，防止插件出现异常时影响dock 的运行状态

```[tasklist]
### Tasks
```

**Comment by justforlxz** [comment]
分享话题：treeland 近况演示
相关链接：https://github.com/linuxdeepin/treeland
话题概述：认证界面的提示；合成器壁纸协议预览；

**Comment by BLumia** [comment]
分享话题：direnv 安利
相关链接：https://direnv.net/
话题概述：介绍 direnv 的作用和使用场景

**Comment by tsic404** [comment]
分享话题：dock 分进程插件介绍
相关链接: https://github.com/linuxdeepin/dde-shell/pull/51
话题描述: dock 分进程加载插件介绍
