### ISSUE TITLE
第24届社区分享会

### ISSUE THREAD

**Issue by wineee** [deepin-community/.meeting#25]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

@wineee 

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2024年01月22日（周一）北京时间15:00
会议号：737 632 626
也可使用入会链接：https://meeting.tencent.com/dm/EY9qFLm6VsjF

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

## 录屏/录音

https://github.com/deepin-community/.meeting/assets/22803888/fac5e85b-f909-443f-b13c-43fcdfd5c47a

## 会议纪要

- [wineee](https://github.com/wineee)
	- 介绍了 treeland 屏幕管理相关的进度，支持  wlr output management 协议
	- 以及客户端（控制中心）初步适配
- [justforlxz](https://github.com/justforlxz)
    - 介绍了 treeland 开发现状，可以运行新的 dock 和 launchpad
    - 新增壁纸设置协议支持和客户端支持

**Comment by wineee** [comment]
分享话题： treeland 屏幕管理相关协议
相关链接:
- https://github.com/vioken/waylib/pull/229
- https://github.com/vioken/waylib/pull/248
- https://github.com/linuxdeepin/treeland/pull/63
- https://github.com/wineee/dde-control-center/pull/1

话题概述：基于 wlr output management 的屏幕管理

**Comment by justforlxz** [comment]
分享话题：treeland 近期进展
相关链接: https://github.com/linuxdeepin/treeland https://github.com/linuxdeepin/dde-shell
话题概述：启动 dock/ launchpad、壁纸设置。
