### ISSUE TITLE
第29届社区分享会

### ISSUE THREAD

**Issue by BLumia** [deepin-community/.meeting#31]
__请回复评论描述自己要分享的内容，以及预计所需要的分享时间__

## 主持人

@BLumia

### 主持人职责

1. 维护会议行为准则
2. 推进会议议程
3. 记录和总结会议纪要
4. 录制会议视频
5. 在会议结束后，到对应的 GitHub Issue 中添加会议纪要和上传会议视频
6. 在会议结束后，在开发者邮件列表的会议召开邮件中回复会议纪要
7. 在会议结束后，到 bbs.deepin.org 发帖展示会议纪要和视频

## 加入方式

位置：线上【腾讯会议】
时间：2024年4月29日（周一）北京时间15:00
会议号：345-973-533
也可使用入会链接：https://work.weixin.qq.com/webapp/tm/HREFbnZGGA9

__入会名称要能体现出自己的GitHub名，或直接与GitHub名保持一致__

## 行为准则

1. 会议以陈述式的分享为目的，不展开讨论，严禁偏题
2. 避免在分享中抛出问题&请求决策，此类事项应当在日常工作中实时进行
3. 禁止流水线式的陈述，无需事无巨细进行描述。建议采用“做了什么”、“为什么这样做”、“达到了什么效果”、“后续还有什么打算”此种模式陈述
4. 禁止随时发言，在每一位分享人结束后允许举手提问，每人仅有一次举手提问的机会，每次问答时间不超过2分钟，对于无法满足的问题，可以会后另行讨论
5. 对于迟到的分享人，将其发言顺序顺延到最后，如直到会议结束依旧未参会（排除提前在邮件列表中请假的情况）则视为放弃本次发言机会。如连续迟到两次，则禁止在下次会议中分享，如无故放弃发言机会，则禁止之后的两次会议中分享
6. 主持人需要根据以上部分规则维护会议秩序，如主持人未尽到自身职责，则在三个月内禁止再次申请为主持人

## 录屏/录音

https://github.com/deepin-community/.meeting/assets/10095765/a023e366-692b-4739-926d-e991d6bf28da

### wineee:

演示了 repology 检索 deepin 仓库的相关特性，并对类如 CVE 展示等特性进行了介绍与说明。

### BLumia:

分享了关于 QML 键盘焦点相关的问题处理注意事项与相关经验。

**Comment by wineee** [comment]
分享话题: repology 支持查询 deepin v23 仓库
相关链接: https://github.com/repology/repology-updater/pull/1357
话题概述: repology 是一个包版本跟踪查询网站，详见 https://repology.org/docs/about

**Comment by BLumia** [comment]
分享话题: QML 键盘焦点程序调试建议分享
相关链接: https://carlschwan.eu/2023/07/30/debugging-the-keyboard-navigation-in-your-qml-application/
话题概述: 
键盘焦点作为一个很容易被忽略的点，相关的调试资料也比较少，本次分享一些相关的调试方式。大致有：

0. （调试无关）keyboard focus 的 nextTab 是当前最深一层的节点响应的，若对于划分多个区域，且每个区域存在多个组件的场景，需要以某种形式（例如属性）将nextTab 期望的焦点组件传递进去
1. 善用 activeFocusItem 属性提供的信息，例如设置其为标题栏名称，即可随实际标点对象变化，方便调试
2. 善用 objectName 与 Accessible.name，不仅可以帮助在上一条中显示更好的组件名称，也可以帮助类似 gammaray 的场景下显示更友好的名称
